export interface ErrorCode {
  code: string;
  category: string;
  statusCode: number;
}

export const errorCodes: ErrorCode[] = [
  { code: 'BODY_NOT_A_STRING_FROM_FUNCTION', category: 'Function', statusCode: 502 },
  { code: 'MIDDLEWARE_INVOCATION_FAILED', category: 'Function', statusCode: 500 },
  { code: 'MIDDLEWARE_INVOCATION_TIMEOUT', category: 'Function', statusCode: 504 },
  { code: 'EDGE_FUNCTION_INVOCATION_FAILED', category: 'Function', statusCode: 500 },
  { code: 'INTERNAL_EDGE_FUNCTION_INVOCATION_FAILED', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_EDGE_FUNCTION_INVOCATION_TIMEOUT', category: 'Internal', statusCode: 504 },
  { code: 'EDGE_FUNCTION_INVOCATION_TIMEOUT', category: 'Function', statusCode: 504 },
  { code: 'FUNCTION_INVOCATION_FAILED', category: 'Function', statusCode: 500 },
  { code: 'FUNCTION_INVOCATION_TIMEOUT', category: 'Function', statusCode: 504 },
  { code: 'FUNCTION_PAYLOAD_TOO_LARGE', category: 'Function', statusCode: 413 },
  { code: 'FUNCTION_RESPONSE_PAYLOAD_TOO_LARGE', category: 'Function', statusCode: 500 },
  { code: 'FUNCTION_RATE_LIMIT', category: 'Function', statusCode: 429 },
  { code: 'INTERNAL_FUNCTION_INVOCATION_FAILED', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_FUNCTION_INVOCATION_TIMEOUT', category: 'Internal', statusCode: 504 },
  { code: 'INTERNAL_FUNCTION_NOT_FOUND', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_FUNCTION_NOT_READY', category: 'Internal', statusCode: 500 },
  { code: 'NO_RESPONSE_FROM_FUNCTION', category: 'Function', statusCode: 502 },
  { code: 'DEPLOYMENT_BLOCKED', category: 'Deployment', statusCode: 403 },
  { code: 'DEPLOYMENT_PAUSED', category: 'Deployment', statusCode: 503 },
  { code: 'DEPLOYMENT_DISABLED', category: 'Deployment', statusCode: 402 },
  { code: 'DEPLOYMENT_NOT_FOUND', category: 'Deployment', statusCode: 404 },
  { code: 'NOT_FOUND', category: 'Deployment', statusCode: 404 },
  { code: 'DEPLOYMENT_DELETED', category: 'Deployment', statusCode: 410 },
  { code: 'DEPLOYMENT_NOT_READY_REDIRECTING', category: 'Deployment', statusCode: 303 },
  { code: 'INTERNAL_DEPLOYMENT_FETCH_FAILED', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_UNARCHIVE_FAILED', category: 'Internal', statusCode: 500 },
  { code: 'INFINITE_LOOP_DETECTED', category: 'Runtime', statusCode: 508 },
  { code: 'INTERNAL_UNEXPECTED_ERROR', category: 'Internal', statusCode: 500 },
  { code: 'DNS_HOSTNAME_EMPTY', category: 'DNS', statusCode: 502 },
  { code: 'DNS_HOSTNAME_NOT_FOUND', category: 'DNS', statusCode: 502 },
  { code: 'DNS_HOSTNAME_RESOLVE_FAILED', category: 'DNS', statusCode: 502 },
  { code: 'DNS_HOSTNAME_RESOLVED_PRIVATE', category: 'DNS', statusCode: 404 },
  { code: 'DNS_HOSTNAME_SERVER_ERROR', category: 'DNS', statusCode: 502 },
  { code: 'TOO_MANY_FORKS', category: 'Routing', statusCode: 502 },
  { code: 'TOO_MANY_FILESYSTEM_CHECKS', category: 'Routing', statusCode: 502 },
  { code: 'INTERNAL_ROUTER_CANNOT_PARSE_PATH', category: 'Internal', statusCode: 500 },
  { code: 'ROUTER_CANNOT_MATCH', category: 'Routing', statusCode: 502 },
  { code: 'ROUTER_EXTERNAL_TARGET_CONNECTION_ERROR', category: 'Routing', statusCode: 502 },
  { code: 'ROUTER_EXTERNAL_TARGET_ERROR', category: 'Routing', statusCode: 502 },
  { code: 'ROUTER_TOO_MANY_HAS_SELECTIONS', category: 'Routing', statusCode: 502 },
  { code: 'ROUTER_EXTERNAL_TARGET_HANDSHAKE_ERROR', category: 'Routing', statusCode: 502 },
  { code: 'INVALID_REQUEST_METHOD', category: 'Request', statusCode: 405 },
  { code: 'MALFORMED_REQUEST_HEADER', category: 'Request', statusCode: 400 },
  { code: 'REQUEST_HEADER_TOO_LARGE', category: 'Request', statusCode: 431 },
  { code: 'INTERNAL_STATIC_REQUEST_FAILED', category: 'Internal', statusCode: 502 },
  { code: 'RESOURCE_NOT_FOUND', category: 'Request', statusCode: 404 },
  { code: 'RANGE_END_NOT_VALID', category: 'Request', statusCode: 416 },
  { code: 'RANGE_GROUP_NOT_VALID', category: 'Request', statusCode: 416 },
  { code: 'RANGE_MISSING_UNIT', category: 'Request', statusCode: 416 },
  { code: 'RANGE_START_NOT_VALID', category: 'Request', statusCode: 416 },
  { code: 'RANGE_UNIT_NOT_SUPPORTED', category: 'Request', statusCode: 416 },
  { code: 'TOO_MANY_RANGES', category: 'Request', statusCode: 416 },
  { code: 'URL_TOO_LONG', category: 'Request', statusCode: 414 },
  { code: 'INVALID_IMAGE_OPTIMIZE_REQUEST', category: 'Image', statusCode: 400 },
  { code: 'INTERNAL_OPTIMIZED_IMAGE_REQUEST_FAILED', category: 'Internal', statusCode: 500 },
  { code: 'OPTIMIZED_EXTERNAL_IMAGE_REQUEST_FAILED', category: 'Image', statusCode: 502 },
  { code: 'OPTIMIZED_EXTERNAL_IMAGE_REQUEST_INVALID', category: 'Image', statusCode: 502 },
  { code: 'OPTIMIZED_EXTERNAL_IMAGE_REQUEST_UNAUTHORIZED', category: 'Image', statusCode: 502 },
  { code: 'OPTIMIZED_EXTERNAL_IMAGE_TOO_MANY_REDIRECTS', category: 'Image', statusCode: 502 },
  { code: 'FALLBACK_BODY_TOO_LARGE', category: 'Cache', statusCode: 502 },
  { code: 'INTERNAL_CACHE_ERROR', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_CACHE_KEY_TOO_LONG', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_CACHE_LOCK_FULL', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_CACHE_LOCK_TIMEOUT', category: 'Internal', statusCode: 500 },
  { code: 'INTERNAL_MISSING_RESPONSE_FROM_CACHE', category: 'Internal', statusCode: 500 }
];
